# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_path', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathpoint',
            name='user_path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='daily_path.UserPath'),
        ),
    ]
